version: '3'
services:
  api:
    build:
      context: .
      dockerfile: python.dockerfile
    command: python manage.py runserver 0.0.0.0:8000 --settings=occurrence_manager.settings_local
    volumes:
      - .:/code:delegated
    ports:
      - "8000:8000"
    env_file:
      - python.env
    depends_on:
      - db

  db:
    image: circleci/postgres:11.5-postgis
    volumes:
      - ./_backups:/srv:ro
    env_file:
      - python.env
    ports:
      - "5440:5432"
