# Generated by Django 3.1.1 on 2020-09-21 14:05

from django.conf import settings
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(blank=True, default='', max_length=100)),
                ('description', models.CharField(blank=True, default='', max_length=100)),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Occurrence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_created=True)),
                ('small_description', models.CharField(blank=True, default='', max_length=100)),
                ('description', models.TextField()),
                ('geo_location', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('waiting_validation', 'Occurrence Waiting Validation'), ('validated', 'Occurrence Validated'), ('closed', 'Occurrence Closed')], default='waiting_validation', max_length=50)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='occurrences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Occurence',
                'verbose_name_plural': 'Occurences',
                'ordering': ['created'],
            },
        ),
    ]
