# Generated by Django 3.1.1 on 2020-09-21 14:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('occurrences', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='occurrence',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='occurrences.category', verbose_name='Category'),
        ),
    ]
