# Generated by Django 3.1.1 on 2020-09-21 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('occurrences', '0003_auto_20200921_2003'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='occurrence',
            name='small_description',
        ),
        migrations.AlterField(
            model_name='occurrence',
            name='description',
            field=models.CharField(default='', max_length=250),
        ),
    ]
