# Generated by Django 3.1.1 on 2020-09-21 23:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('occurrences', '0004_auto_20200921_2004'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='occurrence',
            options={'ordering': ['created'], 'verbose_name': 'Occurrence', 'verbose_name_plural': 'Occurrences'},
        ),
        migrations.AlterField(
            model_name='occurrence',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='occurrences.category', verbose_name='Category'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='occurrence',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
